### ISSUE TITLE
Possibility of extending the solution to all database backends

### ISSUE THREAD

**Issue by tonny1983** [usr42/spring-vault-database-rotate#1]
It's a very success solution to acquire a new database credentials after the old one's lease expired. And further more, because of the refresh mechanism of `HikariDataSource`, new DB connections can replace the old ones without reboot.

Actually, the database credentials like some other secrets backends are property values in Spring Boot application, just as what the [document](https://cloud.spring.io/spring-cloud-vault/reference/html/#vault.config.backends.database-backends) said "Username and password are stored in `xxx.username` and `xxx.password` so using Spring Boot will pick up the generated credentials without further configuration. You can configure the property names by setting `spring.cloud.vault.xxx.username-property` and `spring.cloud.vault.xxx.password-property`." Therefore, should it be a general solution if the spring property of `username` and `password` can be replace by the new one?

I know if using `spring-cloud`, when some config properties changed remotely (e.g. key-value change in `consul`), the spring boot application will automatic obtain the new value and make it be effective (using `@RefreshScope`). However, I'm not sure is there a method to set the `Environment` and refresh it programmatically. If so, your solution should cover all cases but only `HikariDataSource`.

**Comment by tonny1983** [comment]
Finally, I'm afraid I got a solution between your third and fourth solution. It refreshes the Spring Boot application but reboots it, and time cost between them is several seconds vs hundreds milliseconds. It may be an option for these who don't want to reboot the apps and meanwhile cannot use `HikariDataSource`. The source of this can be found in my `spring-vault-demo` project.

**Comment by usr42** [comment]
@tonny1983 Thanks for your comment and proposal and sorry, I wanted to respond earlier, but I did not find the time to investigate deeper.
AFAIK using `@RefreshScope` is not automatically reinitializing the underlaying technologies which use the credentials. Most of them expect the properties to be static and are implemented with that situation in mind. That's why changing these at runtime is not working most of the time.

You can read my blog post for this repo here: https://secrets-as-a-service.com/posts/hashicorp-vault/rotate-dynamic-relational-database-connection-in-spring-at-runtime/

But it sounds like you don't use a relational database or at least not HikariCP, are you?
Which technology/database are you using?

I'll definitively have a look into your repo.

**Comment by tonny1983** [comment]
@usr42 I use reactive MongoDB driver in my demo app but a JDBC driver...
In my opinion,  there are two types of connections to the endpoints: non-pooled connections and pooled connections. 
The so-called "refresh solution" may cover all the cases when uses non-pooled connections, because the connection is created on demand and less reusable, it can always be created with the current valid credentials. 
Then, for the second type, you have already resolved the most part of the cases -- I mean the JDBC pool -- perfectly. The question is whether the other connection pools support the "refresh" function, but I've got no idea about such a general question. However, in my demo case, the `MongoClient` of` Reactive MongoDB Client` represents a pool of connections for MongoDB, and it works properly with the "refresh" solution. And I think it is not very different to verify other Spring Data/Vault supported endpoints.
